# Site settings
title: Neil Isaac
email: mail at neilisaac dot ca
description: software engineer and tinkerer
baseurl: ""
url: "http://neilisaac.ca"
github_username: neilisaac
markdown: kramdown
gems:
  - jekyll-seo-tag
links:
  - title: GitHub
    url: https://github.com/neilisaac
  - title: LinkedIn
    url: https://www.linkedin.com/in/neil-isaac